// app.module.js (your main application JavaScript file)

// =======================================================================
// --- ADD ALL IMPORTS HERE AT THE VERY TOP OF THE FILE ---
// =======================================================================
import { initializeApp } from 'firebase/app';
// Ensure setDoc is imported for creating user profiles
import { getFirestore, serverTimestamp, doc, getDoc, setDoc } from 'firebase/firestore';
import { getAuth, signInWithEmailAndPassword, onAuthStateChanged, createUserWithEmailAndPassword, updatePassword, signOut } from 'firebase/auth';
import { getStorage } from 'firebase/storage';
import { getRemoteConfig } from 'firebase/remote-config';

// -----------------------------------------------------------------------
// --- Firebase Configuration ---
// This now relies *entirely* on the window.NETLIFY_FIREBASE_CONFIG object
// generated by your build-env.sh script from Netlify environment variables.
// There is NO hardcoded fallback here. If window.NETLIFY_FIREBASE_CONFIG is
// not available, an error will be logged and displayed.
// -----------------------------------------------------------------------
const firebaseConfig = window.NETLIFY_FIREBASE_CONFIG;


// *** NEW DEBUG LOGS START (Before Firebase App Initialization) ***
console.log("DEBUG: --- Config Check Before initializeApp ---");
console.log("DEBUG: firebaseConfig object before initialization:");
console.log(firebaseConfig);
console.log("DEBUG: apiKey (from firebaseConfig):", firebaseConfig ? firebaseConfig.apiKey : 'NOT FOUND');
console.log("DEBUG: authDomain (from firebaseConfig):", firebaseConfig ? firebaseConfig.authDomain : 'NOT FOUND');
console.log("DEBUG: projectId (from firebaseConfig):", firebaseConfig ? firebaseConfig.projectId : 'NOT FOUND');
console.log("DEBUG: appId (from firebaseConfig):", firebaseConfig ? firebaseConfig.appId : 'NOT FOUND');
console.log("DEBUG: --- End Config Check ---");
// *** NEW DEBUG LOGS END ***


// Initialize Firebase App and Services
let app;
let auth;
let db;

// Define your Admin User ID - MUST match the UID in your Firebase Authentication and Firestore rules.
// Be careful not to expose this in client-side code if it needs to be highly secret,
// but for checking a specific UID, it's commonly used this way.
const ADMIN_USER_ID = "cEQQHNVXPQfXFhOzO1xBXW";


// Function to hide the loading overlay (declared early for accessibility)
function hideLoadingOverlay() {
    const loadingOverlay = document.getElementById('loading-overlay');
    if (loadingOverlay) {
        loadingOverlay.classList.add('hidden');
    }
}

// Helper function to update UI based on user profile data
async function showContentBasedOnProfile(profileData, uid) {
    const accountPremiumStatusSpan = document.getElementById('account-premium-status');
    const accountNicknameInput = document.getElementById('account-nickname');
    const mainContent = document.getElementById('main-content');
    const paywallContent = document.getElementById('paywall-content');

    let hasAccess = false;

    if (profileData.isPro) {
        hasAccess = true;
        console.log("DEBUG: User is PRO member.");
    } else if (profileData.freeAccessGranted && profileData.freeAccessStartTime) {
        // Check if free access time has not expired (10 minutes)
        const tenMinutesInMillis = 10 * 60 * 1000;
        // Handle Firestore Timestamp or Date.getTime() or Date objects
        const freeAccessStartTimeMillis = profileData.freeAccessStartTime.toMillis ? profileData.freeAccessStartTime.toMillis() : profileData.freeAccessStartTime;
        const freeAccessEndTime = freeAccessStartTimeMillis + tenMinutesInMillis;
        
        if (Date.now() < freeAccessEndTime) {
            hasAccess = true;
            console.log("DEBUG: User has free access remaining.");
        } else {
            console.log("DEBUG: Free access period expired for UID:", uid);
        }
    }

    if (hasAccess) {
        if (paywallContent) paywallContent.classList.add('hidden');
        if (mainContent) mainContent.classList.remove('hidden');
    } else {
        if (paywallContent) paywallContent.classList.remove('hidden');
        if (mainContent) mainContent.classList.add('hidden');
    }

    // Update Account Modal UI if elements exist
    if (accountPremiumStatusSpan) {
        accountPremiumStatusSpan.textContent = profileData.isPro ? 'PRO MEMBER' : 'STANDARD';
        if (profileData.isPro) accountPremiumStatusSpan.classList.add('text-green-600');
        else accountPremiumStatusSpan.classList.remove('text-green-600');
    }
    if (accountNicknameInput) accountNicknameInput.value = profileData.nickname || '';
}


// Check if firebaseConfig is valid before initializing
if (!firebaseConfig || Object.keys(firebaseConfig).length === 0 || !firebaseConfig.apiKey) {
    console.error("Firebase configuration is missing or invalid. Please ensure Netlify environment variables are correctly set and env-config.js is generated.");
    // Display an error message on the page if config is missing
    document.addEventListener('DOMContentLoaded', () => { // Ensure DOM is ready to display error
        const errorDisplay = document.getElementById('firebase-init-error-text');
        if (errorDisplay) {
            errorDisplay.textContent = "Firebase configuration is missing or API Key is empty. App cannot start. Check console for details.";
            document.getElementById('firebase-init-error-display').classList.remove('hidden');
        }
        hideLoadingOverlay(); // Hide loading overlay even if initialization fails
    });
} else {
    try {
        app = initializeApp(firebaseConfig);
        auth = getAuth(app);
        db = getFirestore(app);
        // Uncomment if you use Storage or Remote Config
        // const storage = getStorage(app);
        // const remoteConfig = getRemoteConfig(app);
        console.log("DEBUG: Firebase App initialized successfully.");
    } catch (e) {
        console.error("DEBUG: Failed to initialize Firebase App:", e);
        document.addEventListener('DOMContentLoaded', () => {
            const errorDisplay = document.getElementById('firebase-init-error-text');
            if (errorDisplay) {
                errorDisplay.textContent = `Firebase initialization failed: ${e.message}. Check console for full error.`;
                document.getElementById('firebase-init-error-display').classList.remove('hidden');
            }
            hideLoadingOverlay(); // Hide loading overlay if initialization fails
        });
    }
}


document.addEventListener('DOMContentLoaded', () => {
    // --- Get common DOM elements ---
    const loginForm = document.getElementById('login-form');
    const loginEmailInput = document.getElementById('login-email');
    const loginPasswordInput = document.getElementById('login-password');
    const loginErrorDisplay = document.getElementById('login-error');
    const headerAuthBtn = document.getElementById('header-auth-btn');
    const accountBtn = document.getElementById('account-btn');
    const zeusAvatarSvg = document.getElementById('zeus-avatar-svg');
    const logoutBtn = document.getElementById('logout-btn');
    const accountModal = document.getElementById('account-modal');
    const accountNewPasswordInput = document.getElementById('account-new-password');
    const accountPasswordError = document.getElementById('account-password-error');
    const updatePasswordBtn = document.getElementById('update-password-btn');
    const loginModal = document.getElementById('login-modal');
    const showSignupBtn = document.getElementById('show-signup'); // Get the "Sign Up" button

// <<< NEW TTS/AUDIO CODE HERE >>>
    // NEW: Get elements for TTS and Audio
    const ttsInput = document.getElementById('tts-input');
    const ttsButton = document.getElementById('tts-button');
    const thunderAudio = document.getElementById('thunder-audio');

    // Initialize SpeechSynthesis API
    const synth = window.speechSynthesis;
    let zeusVoice = null; // To store the selected voice for Zeus

    // Function to set Zeus's voice
    function setZeusVoice() {
        if (!synth) {
            console.warn("DEBUG: SpeechSynthesis API not supported in this browser.");
            if (ttsButton) ttsButton.disabled = true; // Disable button if not supported
            return;
        }

        const voices = synth.getVoices();
        if (voices.length === 0) {
            console.log("DEBUG: No voices available yet, waiting for onvoiceschanged.");
            return;
        }

        // Try to find a deep, powerful-sounding male voice.
        zeusVoice = voices.find(voice => 
            voice.lang.startsWith('en') && 
            (voice.name.includes('Google US English') || voice.name.includes('Alex') || voice.name.includes('Daniel') || voice.name.includes('Zira') || voice.name.includes('पुरुष') ) &&
            (voice.name.toLowerCase().includes('male') || !voice.name.toLowerCase().includes('female'))
        );

        // Fallback to a default English voice if a specific "Zeus" voice isn't found
        if (!zeusVoice) {
            zeusVoice = voices.find(voice => voice.lang === 'en-US' || voice.lang === 'en-GB') || voices[0];
        }
        
        if (zeusVoice) {
            console.log("DEBUG: Zeus Voice set to:", zeusVoice.name);
            if (ttsButton) ttsButton.disabled = false; // Enable button once voice is set
        } else {
            console.warn("DEBUG: Could not find a suitable Zeus voice. Speech synthesis might not work.");
            if (ttsButton) ttsButton.disabled = true;
        }
    }

    // Load voices after they are available (they load asynchronously)
    if (synth) {
        synth.onvoiceschanged = setZeusVoice;
        // Call setZeusVoice immediately. If voices aren't loaded, it will return early and
        // onvoiceschanged will call it again when they are ready.
        setZeusVoice(); 
    } else {
        console.warn("DEBUG: SpeechSynthesis API not available.");
        if (ttsButton) ttsButton.disabled = true;
    }
    // <<< END NEW TTS/AUDIO CODE >>>


    // Set initial window properties
    window.isLoggedIn = false;
    window.currentUserId = null;

    // *** NEW DEBUG LOGS START (Within DOMContentLoaded) ***
    console.log("DEBUG: --- Config Check Within DOMContentLoaded ---");
    console.log("DEBUG: DOMContentLoaded fired. window.NETLIFY_FIREBASE_CONFIG:", window.NETLIFY_FIREBASE_CONFIG);
    console.log("DEBUG: effective firebaseConfig within DOMContentLoaded:", firebaseConfig);
    console.log("DEBUG: auth object status (should be defined if init successful):", auth);
    console.log("DEBUG: db object status (should be defined if init successful):", db);
    console.log("DEBUG: --- End Config Check ---");
    // *** NEW DEBUG LOGS END ***


    // Only set up auth state listener if auth was successfully initialized
    if (auth) {
        // -----------------------------------------------------------------------
        // --- onAuthStateChanged Listener ---
        // -----------------------------------------------------------------------
        onAuthStateChanged(auth, async (user) => {
            console.log("Authentication state changed. User:", user ? user.uid : "No user");

            // Update global state
            window.isLoggedIn = !!user;
            window.currentUserId = user ? user.uid : null;

            // Update UI visibility based on auth state
            if (user) {
                // User is signed in
                if (headerAuthBtn) headerAuthBtn.classList.add('hidden');
                if (accountBtn) accountBtn.classList.remove('hidden');
                if (zeusAvatarSvg) zeusAvatarSvg.style.opacity = '1';
                if (logoutBtn) logoutBtn.classList.remove('hidden');

                // Example of populating account details from user object directly
                const accountUidSpan = document.getElementById('account-uid');
                if (accountUidSpan) accountUidSpan.textContent = user.uid;

                // Optionally fetch user profile data from Firestore here if needed for UI
                if (db) { // Ensure db is initialized before using
                    try {
                        // Using firebaseConfig.appId as the 'artifacts' sub-collection ID
                        const userProfileDocRef = doc(db, 'artifacts', firebaseConfig.appId, 'users', user.uid, 'profile', 'info');
                        const userProfileSnap = await getDoc(userProfileDocRef);

                        // Determine if the current user is the admin
                        const isAdminUser = (user.uid === ADMIN_USER_ID);

                        if (!userProfileSnap.exists()) {
                            console.log("DEBUG: User profile document not found. Creating default profile for UID:", user.uid);
                            
                            // Create a default profile document if it doesn't exist
                            await setDoc(userProfileDocRef, {
                                uid: user.uid,
                                email: user.email,
                                nickname: 'New User',
                                isPro: isAdminUser, // Set isPro based on admin check
                                tourCompleted: false,
                                freeAccessGranted: !isAdminUser, // Grant free access if NOT admin
                                freeAccessStartTime: isAdminUser ? null : serverTimestamp(), // Set start time only for non-admins
                                createdAt: serverTimestamp()
                            });

                            // Create a local representation of the profile data for immediate use
                            // Use Date.now() for freeAccessStartTime if not admin, for client-side comparison
                            const defaultProfileData = {
                                uid: user.uid,
                                email: user.email,
                                nickname: 'New User',
                                isPro: isAdminUser,
                                tourCompleted: false,
                                freeAccessGranted: !isAdminUser,
                                freeAccessStartTime: isAdminUser ? null : Date.now(),
                                createdAt: Date.now()
                            };
                            await showContentBasedOnProfile(defaultProfileData, user.uid); // Call helper function
                            console.log(`DEBUG: Default user profile created. Is Admin: ${isAdminUser}, Is Pro: ${isAdminUser}, Free Access Granted: ${!isAdminUser}.`);

                        } else {
                            // EXISTING CODE: Profile exists, fetch and use it
                            const profileData = userProfileSnap.data();
                            console.log("DEBUG: User profile data from Firestore:", profileData);
                            await showContentBasedOnProfile(profileData, user.uid); // Call helper function
                        }

                    } catch (error) {
                        console.error("DEBUG: Error fetching or creating user profile from Firestore:", error);
                        // If there's an error, assume no access and show paywall
                        if (paywallContent) paywallContent.classList.remove('hidden');
                        if (mainContent) mainContent.classList.add('hidden');
                    }
                }

            } else {
                // User is signed out
                if (headerAuthBtn) headerAuthBtn.classList.remove('hidden');
                if (accountBtn) accountBtn.classList.add('hidden');
                if (zeusAvatarSvg) zeusAvatarSvg.style.opacity = '0';
                if (logoutBtn) logoutBtn.classList.add('hidden');

                if (loginModal) loginModal.classList.add('hidden');
                if (accountModal) accountModal.classList.add('hidden');

                // If user is signed out, show paywall
                const mainContent = document.getElementById('main-content'); // Ensure these are defined here too
                const paywallContent = document.getElementById('paywall-content'); // in case they were not globally accessible
                if (paywallContent) paywallContent.classList.remove('hidden');
                if (mainContent) mainContent.classList.add('hidden');
            }
            hideLoadingOverlay(); // Hide the loading overlay once auth state is determined
        });

        // --- Sign Out Button Listener ---
        if (logoutBtn) {
            logoutBtn.addEventListener('click', async () => {
                try {
                    await signOut(auth);
                    console.log("DEBUG: User signed out.");
                } catch (error) {
                    console.error("DEBUG: Error signing out:", error);
                }
            });
        }
    } else {
        // If auth was not initialized, hide overlay anyway
        console.warn("DEBUG: Firebase Auth not initialized, onAuthStateChanged listener skipped.");
        hideLoadingOverlay();
        // Also show paywall if auth not initialized
        const mainContent = document.getElementById('main-content');
        const paywallContent = document.getElementById('paywall-content');
        if (paywallContent) paywallContent.classList.remove('hidden');
        if (mainContent) mainContent.classList.add('hidden');
    }


    // *** Register button event listener ***
    const registerAuthBtn = document.getElementById('register-auth-btn');
    if (registerAuthBtn && auth) { // Ensure auth is initialized before attaching listener
        registerAuthBtn.addEventListener('click', async () => {
            console.log("DEBUG: Register button clicked. Initiating registration process.");
            if (loginErrorDisplay) {
                loginErrorDisplay.textContent = '';
                loginErrorDisplay.classList.remove('text-green-500');
                loginErrorDisplay.classList.add('text-red-500');
            }

            const email = loginEmailInput.value;
            const password = loginPasswordInput.value;

            if (!email || !password) {
                loginErrorDisplay.textContent = 'Please enter both email and password for registration.';
                return;
            }

            /* // Password validation commented out as per your previous code
            try {
                const passwordPolicyStatus = await validatePassword(auth, password);
                if (!passwordPolicyStatus.isValid) {
                    let feedback = "Password does not meet requirements: ";
                    if (passwordPolicyStatus.meetsMinPasswordLength === false) feedback += "minimum length, ";
                    if (passwordPolicyStatus.containsLowercaseLetter === false) feedback += "lowercase, ";
                    if (passwordPolicyStatus.containsUppercaseLetter === false) feedback += "uppercase, ";
                    if (passwordPolicyStatus.containsNumericCharacter === false) feedback += "numeric, ";
                    if (passwordPolicyStatus.containsNonAlphanumericCharacter === false) feedback += "special character, ";
                    loginErrorDisplay.textContent = feedback.slice(0, -2) + ".";
                    return;
                }
            } catch (policyError) {
                console.error("DEBUG: Error validating password policy:", policyError);
                loginErrorDisplay.textContent = "Error checking password policy.";
                return;
            }
            */

            try {
                const userCredential = await createUserWithEmailAndPassword(auth, email, password);
                const user = userCredential.user;
                console.log("DEBUG: New user registered:", user.uid);
                loginErrorDisplay.textContent = 'Registration successful! You are now logged in.';
                loginErrorDisplay.classList.remove('text-red-500');
                loginErrorDisplay.classList.add('text-green-500');
                if (loginModal) loginModal.classList.add('hidden');
            } catch (error) {
                console.error("DEBUG: Registration failed:", error.code, error.message);
                loginErrorDisplay.classList.remove('text-green-500');
                loginErrorDisplay.classList.add('text-red-500');
                switch(error.code) {
                    case 'auth/email-already-in-use':
                        loginErrorDisplay.textContent = 'This email is already registered. Try logging in.';
                        break;
                    case 'auth/invalid-email':
                        loginErrorDisplay.textContent = 'Please enter a valid email address.';
                        break;
                    case 'auth/weak-password':
                        loginErrorDisplay.textContent = 'Password is too weak. Please choose a stronger one (min 6 chars recommended).';
                        break;
                    default:
                        loginErrorDisplay.textContent = `Registration failed: ${error.message}`;
                        break;
                }
            }
        });
    }

    if (loginForm && auth) { // Ensure auth is initialized before attaching listener
        loginForm.addEventListener('submit', async (event) => {
            event.preventDefault();
            console.log("DEBUG: Login form submitted via JavaScript, default browser action prevented.");

            if (loginErrorDisplay) {
                loginErrorDisplay.textContent = '';
                loginErrorDisplay.classList.remove('text-green-500');
                loginErrorDisplay.classList.add('text-red-500');
            }

            const email = loginEmailInput.value;
            const password = loginPasswordInput.value;

            if (!email || !password) {
                if (loginErrorDisplay) {
                    loginErrorDisplay.textContent = 'Please enter both email and password.';
                }
                return;
            }

            try {
                const userCredential = await signInWithEmailAndPassword(auth, email, password);
                const user = userCredential.user;
                console.log("DEBUG: User logged in:", user.uid);
                if (loginModal) loginModal.classList.add('hidden');
            } catch (error) {
                const errorCode = error.code;
                const errorMessage = error.message;
                console.error("DEBUG: Login failed:", errorCode, errorMessage);
                if (loginErrorDisplay) {
                    switch(errorCode) {
                        case 'auth/user-not-found':
                        case 'auth/wrong-password':
                            loginErrorDisplay.textContent = 'Invalid email or password.';
                            break;
                        case 'auth/invalid-email':
                            loginErrorDisplay.textContent = 'Please enter a valid email address.';
                            break;
                        case 'auth/too-many-requests':
                            loginErrorDisplay.textContent = 'Too many failed login attempts. Please try again later.';
                            break;
                        case 'auth/user-disabled':
                            loginErrorDisplay.textContent = 'Your account has been disabled.';
                            break;
                        default:
                            loginErrorDisplay.textContent = `Login failed: ${errorMessage}`;
                            break;
                    }
                }
            }
        });
    }

    if (headerAuthBtn) {
        headerAuthBtn.addEventListener('click', () => {
            if (loginModal) loginModal.classList.remove('hidden');
            if (loginEmailInput) loginEmailInput.value = '';
            if (loginPasswordInput) loginPasswordInput.value = '';
            if (loginErrorDisplay) {
                loginErrorDisplay.textContent = '';
                loginErrorDisplay.classList.remove('text-green-500');
                loginErrorDisplay.classList.add('text-red-500');
            }
        });
    }

    // --- "Sign Up" Link Listener ---
    if (showSignupBtn) { // Only set up if the button element actually exists
        showSignupBtn.addEventListener('click', () => {
            // Clear any previous login errors
            if (loginErrorDisplay) {
                loginErrorDisplay.textContent = 'Enter your email and a new password, then click "Register" to create an account.';
                // Change error text color to green for a helpful message
                loginErrorDisplay.classList.remove('text-red-500');
                loginErrorDisplay.classList.add('text-green-500');
            }

            // Clear email and password fields for a fresh registration attempt
            if (loginEmailInput) {
                loginEmailInput.value = '';
                loginEmailInput.focus(); // Immediately focus on the email input for user convenience
            }
            if (loginPasswordInput) {
                loginPasswordInput.value = '';
            }
            // Ensure the login modal is visible in case it was hidden for some reason
            if (loginModal) {
                loginModal.classList.remove('hidden');
            }
        });
    }


    // *** Account button event listener ***
    if (accountBtn) {
        accountBtn.addEventListener('click', () => {
            if (accountModal) {
                accountModal.classList.remove('hidden');
                // Populate account details when modal opens
                const accountUidSpan = document.getElementById('account-uid');
                const accountPremiumStatusSpan = document.getElementById('account-premium-status');
                const accountNicknameInput = document.getElementById('account-nickname');

                if (auth && auth.currentUser) { // Check auth and currentUser before accessing
                    if (accountUidSpan) accountUidSpan.textContent = auth.currentUser.uid;
                    // For premium status and nickname, you would fetch from Firestore here as needed
                    // (This logic is already in onAuthStateChanged for initial load, but can be repeated here if needed for re-opening modal)
                }
            }
        });
    }

    // *** Change Password functionality ***
    // (This is the block you're looking for, now updated to listen to the form's submit event)
    const updatePasswordForm = document.getElementById('update-password-form'); // This line was added
    if (updatePasswordForm && auth) { // Changed from updatePasswordBtn to updatePasswordForm
        updatePasswordForm.addEventListener('submit', async (event) => { // Changed from 'click' to 'submit'
            event.preventDefault();

            accountPasswordError.textContent = '';
            accountPasswordError.classList.remove('text-green-500');
            accountPasswordError.classList.add('text-red-500');

            const newPassword = accountNewPasswordInput.value;
            if (!newPassword) {
                accountPasswordError.textContent = 'Please enter a new password.';
                return;
            }

            const user = auth.currentUser;

            if (user) {
                /* // Password validation commented out as per your previous code
                try {
                    const passwordPolicyStatus = await validatePassword(auth, newPassword);
                    if (!passwordPolicyStatus.isValid) {
                        let feedback = "Password does not meet requirements: ";
                        if (passwordPolicyStatus.meetsMinPasswordLength === false) feedback += "minimum length, ";
                        if (passwordPolicyStatus.containsLowercaseLetter === false) feedback += "lowercase, ";
                        if (passwordPolicyStatus.containsUppercaseLetter === false) feedback += "uppercase, ";
                        if (passwordPolicyStatus.containsNumericCharacter === false) feedback += "numeric, ";
                        if (passwordPolicyStatus.containsNonAlphanumericCharacter === false) feedback += "special character, ";
                        loginErrorDisplay.textContent = feedback.slice(0, -2) + ".";
                        return;
                    }
                } catch (policyError) {
                    console.error("DEBUG: Error validating password policy:", policyError);
                    accountPasswordError.textContent = "Error checking password policy for new password.";
                    return;
                }
                */

                try {
                    await updatePassword(user, newPassword);
                    accountPasswordError.textContent = 'Password updated successfully!';
                    accountPasswordError.classList.remove('text-red-500');
                    accountPasswordError.classList.add('text-green-500');
                    accountNewPasswordInput.value = '';
                    console.log("DEBUG: User password updated.");
                } catch (error) {
                    console.error("DEBUG: Error updating password:", error.code, error.message);
                    accountPasswordError.classList.remove('text-green-500');
                    accountPasswordError.classList.add('text-red-500');
                    if (error.code === 'auth/weak-password') {
                        accountPasswordError.textContent = 'New password is too weak. Please choose a stronger one.';
                    } else if (error.code === 'auth/requires-recent-login') {
                         accountPasswordError.textContent = 'This is a security-sensitive operation. Please log out and log back in, then try changing your password again.';
                    } else {
                        accountPasswordError.textContent = `Error updating password: ${error.message}`;
                    }
                }
            } else {
                accountPasswordError.textContent = 'No user is currently logged in. Please log in to change your password.';
            }
        });
    }
    // *** Close Account Modal button listener ***
    const closeAccountModalBtn = document.getElementById('close-account-modal-btn');
    if (closeAccountModalBtn) {
        closeAccountModalBtn.addEventListener('click', () => {
            if (accountModal) {
                accountModal.classList.add('hidden');
                accountNewPasswordInput.value = '';
                accountPasswordError.textContent = '';
                accountPasswordError.classList.remove('text-green-500');
                accountPasswordError.classList.add('text-red-500');
            }
        });
    }

    const closeLoginModalBtn = document.getElementById('close-login-modal-btn');
    if (closeLoginModalBtn) {
        closeLoginModalBtn.addEventListener('click', () => {
            if (loginModal) loginModal.classList.add('hidden');
            if (loginErrorDisplay) {
                loginErrorDisplay.textContent = '';
                loginErrorDisplay.classList.remove('text-green-500');
                loginErrorDisplay.classList.add('text-red-500');
            }
            if (loginEmailInput) loginEmailInput.value = '';
            if (loginPasswordInput) loginPasswordInput.value = '';
        });
    }

    
    // Initialize any other UI components that don't depend on auth state
    const mainContent = document.getElementById('main-content');
    const paywallContent = document.getElementById('paywall-content');

    // Example: Initially hide main content and show paywall, then auth state will adjust
    // This logic might be better placed within your onAuthStateChanged listener
    // or triggered by it if it depends on user's PRO status.
    if (mainContent) mainContent.classList.add('hidden');
    if (paywallContent) paywallContent.classList.remove('hidden');
});