
// app.module.js (your main application JavaScript file)

// =======================================================================
// --- ADD ALL IMPORTS HERE AT THE VERY TOP OF THE FILE ---
// =======================================================================
import { initializeApp } from 'firebase/app';
import { getFirestore, serverTimestamp as firestoreServerTimestamp, doc, getDoc } from 'firebase/firestore';
import { getAuth, signInWithEmailAndPassword, onAuthStateChanged, validatePassword, createUserWithEmailAndPassword, updatePassword, signOut } from 'firebase/auth';
import { getStorage } from 'firebase/storage';
import { getRemoteConfig } from 'firebase/remote-config';

// -----------------------------------------------------------------------
// --- Firebase Configuration ---
// These are your specific values, either hardcoded here or preferably
// pulled from window.NETLIFY_FIREBASE_CONFIG if generated by your build script.
// For direct local testing, ensure these are correct.
// -----------------------------------------------------------------------
const hardcodedFirebaseConfig = {
    apiKey: "AIzaSyDbt0ITM9G4LOZTlXuAGGvuO80uazFpZSs",
    authDomain: "sntlmoexclusivesportsgrid.firebaseapp.com",
    projectId: "sntlmoexclusivesportsgrid",
    storageBucket: "sntlmoexclusivesportsgrid.firebasestorage.app",
    messagingSenderId: "735791748207",
    appId: "1:735791748207:web:74fd6412684db238b6e99a",
    measurementId: "G-T8RJPDPL4G" // Note: measurementId is for Analytics and not used by Firebase SDK init itself
};

// Use the config from Netlify environment variables if available, otherwise use hardcoded.
// In a production Netlify environment, window.NETLIFY_FIREBASE_CONFIG should be populated.
const firebaseConfig = window.NETLIFY_FIREBASE_CONFIG || hardcodedFirebaseConfig;


// *** NEW DEBUG LOGS START (Before Firebase App Initialization) ***
console.log("DEBUG: --- Config Check Before initializeApp ---");
console.log("DEBUG: firebaseConfig object before initialization:");
console.log(firebaseConfig);
console.log("DEBUG: apiKey (from firebaseConfig):", firebaseConfig.apiKey);
console.log("DEBUG: authDomain (from firebaseConfig):", firebaseConfig.authDomain);
console.log("DEBUG: projectId (from firebaseConfig):", firebaseConfig.projectId);
console.log("DEBUG: appId (from firebaseConfig):", firebaseConfig.appId);
console.log("DEBUG: --- End Config Check ---");
// *** NEW DEBUG LOGS END ***


// Initialize Firebase App and Services
let app;
let auth;
let db;

// Function to hide the loading overlay (declared early for accessibility)
function hideLoadingOverlay() {
    const loadingOverlay = document.getElementById('loading-overlay');
    if (loadingOverlay) {
        loadingOverlay.classList.add('hidden');
    }
}

// Check if firebaseConfig is valid before initializing
if (!firebaseConfig || Object.keys(firebaseConfig).length === 0 || !firebaseConfig.apiKey) {
    console.error("Firebase configuration is missing or invalid. Please check Netlify environment variables and env-config.js generation, or ensure hardcodedFirebaseConfig is complete.");
    // Display an error message on the page if config is missing
    document.addEventListener('DOMContentLoaded', () => { // Ensure DOM is ready to display error
        const errorDisplay = document.getElementById('firebase-init-error-text');
        if (errorDisplay) {
            errorDisplay.textContent = "Firebase configuration is missing. App cannot start. Check console for details.";
            document.getElementById('firebase-init-error-display').classList.remove('hidden');
        }
        hideLoadingOverlay(); // Hide loading overlay even if initialization fails
    });
} else {
    try {
        app = initializeApp(firebaseConfig);
        auth = getAuth(app);
        db = getFirestore(app);
        // Uncomment if you use Storage or Remote Config
        // const storage = getStorage(app);
        // const remoteConfig = getRemoteConfig(app);
        console.log("DEBUG: Firebase App initialized successfully.");
    } catch (e) {
        console.error("DEBUG: Failed to initialize Firebase App:", e);
        document.addEventListener('DOMContentLoaded', () => {
            const errorDisplay = document.getElementById('firebase-init-error-text');
            if (errorDisplay) {
                errorDisplay.textContent = `Firebase initialization failed: ${e.message}. Check console for full error.`;
                document.getElementById('firebase-init-error-display').classList.remove('hidden');
            }
            hideLoadingOverlay(); // Hide loading overlay if initialization fails
        });
    }
}


document.addEventListener('DOMContentLoaded', () => {
    // --- Get common DOM elements ---
    const loginForm = document.getElementById('login-form');
    const loginEmailInput = document.getElementById('login-email');
    const loginPasswordInput = document.getElementById('login-password');
    const loginErrorDisplay = document.getElementById('login-error');
    const headerAuthBtn = document.getElementById('header-auth-btn');
    const accountBtn = document.getElementById('account-btn');
    const zeusAvatarSvg = document.getElementById('zeus-avatar-svg');
    const logoutBtn = document.getElementById('logout-btn');
    const accountModal = document.getElementById('account-modal');
    const accountNewPasswordInput = document.getElementById('account-new-password');
    const accountPasswordError = document.getElementById('account-password-error');
    const updatePasswordBtn = document.getElementById('update-password-btn');
    const loginModal = document.getElementById('login-modal');

    // Set initial window properties
    window.isLoggedIn = false;
    window.currentUserId = null;

    // *** NEW DEBUG LOGS START (Within DOMContentLoaded) ***
    console.log("DEBUG: --- Config Check Within DOMContentLoaded ---");
    console.log("DEBUG: DOMContentLoaded fired. window.NETLIFY_FIREBASE_CONFIG:", window.NETLIFY_FIREBASE_CONFIG);
    console.log("DEBUG: effective firebaseConfig within DOMContentLoaded:", firebaseConfig);
    console.log("DEBUG: auth object status (should be defined if init successful):", auth);
    console.log("DEBUG: db object status (should be defined if init successful):", db);
    console.log("DEBUG: --- End Config Check ---");
    // *** NEW DEBUG LOGS END ***


    // Only set up auth state listener if auth was successfully initialized
    if (auth) {
        // -----------------------------------------------------------------------
        // --- onAuthStateChanged Listener ---
        // -----------------------------------------------------------------------
        onAuthStateChanged(auth, async (user) => {
            console.log("Authentication state changed. User:", user ? user.uid : "No user");

            // Update global state
            window.isLoggedIn = !!user;
            window.currentUserId = user ? user.uid : null;

            // Update UI visibility based on auth state
            if (user) {
                // User is signed in
                if (headerAuthBtn) headerAuthBtn.classList.add('hidden');
                if (accountBtn) accountBtn.classList.remove('hidden');
                if (zeusAvatarSvg) zeusAvatarSvg.style.opacity = '1';
                if (logoutBtn) logoutBtn.classList.remove('hidden');

                // Example of populating account details from user object directly
                const accountUidSpan = document.getElementById('account-uid');
                if (accountUidSpan) accountUidSpan.textContent = user.uid;

                // Optionally fetch user profile data from Firestore here if needed for UI
                if (db) { // Ensure db is initialized before using
                    try {
                        // Using firebaseConfig.appId as the 'artifacts' sub-collection ID
                        const userProfileDocRef = doc(db, 'artifacts', firebaseConfig.appId, 'users', user.uid, 'profile', 'info');
                        const userProfileSnap = await getDoc(userProfileDocRef);
                        const accountPremiumStatusSpan = document.getElementById('account-premium-status');
                        const accountNicknameInput = document.getElementById('account-nickname');

                        if (userProfileSnap.exists()) {
                            const profileData = userProfileSnap.data();
                            console.log("DEBUG: User profile data from Firestore:", profileData);
                            if (accountPremiumStatusSpan) {
                                accountPremiumStatusSpan.textContent = profileData.isPro ? 'PRO MEMBER' : 'STANDARD';
                                if (profileData.isPro) accountPremiumStatusSpan.classList.add('text-green-600');
                                else accountPremiumStatusSpan.classList.remove('text-green-600');
                            }
                            if (accountNicknameInput) accountNicknameInput.value = profileData.nickname || '';
                        } else {
                             if (accountPremiumStatusSpan) accountPremiumStatusSpan.textContent = 'STANDARD';
                             console.log("DEBUG: User profile document not found in Firestore for UID:", user.uid);
                        }
                    } catch (error) {
                        console.error("DEBUG: Error fetching user profile from Firestore:", error);
                    }
                }

            } else {
                // User is signed out
                if (headerAuthBtn) headerAuthBtn.classList.remove('hidden');
                if (accountBtn) accountBtn.classList.add('hidden');
                if (zeusAvatarSvg) zeusAvatarSvg.style.opacity = '0';
                if (logoutBtn) logoutBtn.classList.add('hidden');

                if (loginModal) loginModal.classList.add('hidden');
                if (accountModal) accountModal.classList.add('hidden');
            }
            hideLoadingOverlay(); // Hide the loading overlay once auth state is determined
        });

        // --- Sign Out Button Listener ---
        if (logoutBtn) {
            logoutBtn.addEventListener('click', async () => {
                try {
                    await signOut(auth);
                    console.log("DEBUG: User signed out.");
                } catch (error) {
                    console.error("DEBUG: Error signing out:", error);
                }
            });
        }
    } else {
        // If auth was not initialized, hide overlay anyway
        console.warn("DEBUG: Firebase Auth not initialized, onAuthStateChanged listener skipped.");
        hideLoadingOverlay();
    }


    // *** Register button event listener ***
    const registerAuthBtn = document.getElementById('register-auth-btn');
    if (registerAuthBtn && auth) { // Ensure auth is initialized before attaching listener
        registerAuthBtn.addEventListener('click', async () => {
            console.log("DEBUG: Register button clicked. Initiating registration process.");
            if (loginErrorDisplay) {
                loginErrorDisplay.textContent = '';
                loginErrorDisplay.classList.remove('text-green-500');
                loginErrorDisplay.classList.add('text-red-500');
            }

            const email = loginEmailInput.value;
            const password = loginPasswordInput.value;

            if (!email || !password) {
                loginErrorDisplay.textContent = 'Please enter both email and password for registration.';
                return;
            }

            /* // Password validation commented out as per your previous code
            try {
                const passwordPolicyStatus = await validatePassword(auth, password);
                if (!passwordPolicyStatus.isValid) {
                    let feedback = "Password does not meet requirements: ";
                    if (passwordPolicyStatus.meetsMinPasswordLength === false) feedback += "minimum length, ";
                    if (passwordPolicyStatus.containsLowercaseLetter === false) feedback += "lowercase, ";
                    if (passwordPolicyStatus.containsUppercaseLetter === false) feedback += "uppercase, ";
                    if (passwordPolicyStatus.containsNumericCharacter === false) feedback += "numeric, ";
                    if (passwordPolicyStatus.containsNonAlphanumericCharacter === false) feedback += "special character, ";
                    loginErrorDisplay.textContent = feedback.slice(0, -2) + ".";
                    return;
                }
            } catch (policyError) {
                console.error("DEBUG: Error validating password policy:", policyError);
                loginErrorDisplay.textContent = "Error checking password policy.";
                return;
            }
            */

            try {
                const userCredential = await createUserWithEmailAndPassword(auth, email, password);
                const user = userCredential.user;
                console.log("DEBUG: New user registered:", user.uid);
                loginErrorDisplay.textContent = 'Registration successful! You are now logged in.';
                loginErrorDisplay.classList.remove('text-red-500');
                loginErrorDisplay.classList.add('text-green-500');
                if (loginModal) loginModal.classList.add('hidden');
            } catch (error) {
                console.error("DEBUG: Registration failed:", error.code, error.message);
                loginErrorDisplay.classList.remove('text-green-500');
                loginErrorDisplay.classList.add('text-red-500');
                switch(error.code) {
                    case 'auth/email-already-in-use':
                        loginErrorDisplay.textContent = 'This email is already registered. Try logging in.';
                        break;
                    case 'auth/invalid-email':
                        loginErrorDisplay.textContent = 'Please enter a valid email address.';
                        break;
                    case 'auth/weak-password':
                        loginErrorDisplay.textContent = 'Password is too weak. Please choose a stronger one (min 6 chars recommended).';
                        break;
                    default:
                        loginErrorDisplay.textContent = `Registration failed: ${error.message}`;
                        break;
                }
            }
        });
    }

    if (loginForm && auth) { // Ensure auth is initialized before attaching listener
        loginForm.addEventListener('submit', async (event) => {
            event.preventDefault();
            console.log("DEBUG: Login form submitted via JavaScript, default browser action prevented.");

            if (loginErrorDisplay) {
                loginErrorDisplay.textContent = '';
                loginErrorDisplay.classList.remove('text-green-500');
                loginErrorDisplay.classList.add('text-red-500');
            }

            const email = loginEmailInput.value;
            const password = loginPasswordInput.value;

            if (!email || !password) {
                if (loginErrorDisplay) {
                    loginErrorDisplay.textContent = 'Please enter both email and password.';
                }
                return;
            }

            try {
                const userCredential = await signInWithEmailAndPassword(auth, email, password);
                const user = userCredential.user;
                console.log("DEBUG: User logged in:", user.uid);
                if (loginModal) loginModal.classList.add('hidden');
            } catch (error) {
                const errorCode = error.code;
                const errorMessage = error.message;
                console.error("DEBUG: Login failed:", errorCode, errorMessage);
                if (loginErrorDisplay) {
                    switch(errorCode) {
                        case 'auth/user-not-found':
                        case 'auth/wrong-password':
                            loginErrorDisplay.textContent = 'Invalid email or password.';
                            break;
                        case 'auth/invalid-email':
                            loginErrorDisplay.textContent = 'Please enter a valid email address.';
                            break;
                        case 'auth/too-many-requests':
                            loginErrorDisplay.textContent = 'Too many failed login attempts. Please try again later.';
                            break;
                        case 'auth/user-disabled':
                            loginErrorDisplay.textContent = 'Your account has been disabled.';
                            break;
                        default:
                            loginErrorDisplay.textContent = `Login failed: ${errorMessage}`;
                            break;
                    }
                }
            }
        });
    }

    if (headerAuthBtn) {
        headerAuthBtn.addEventListener('click', () => {
            if (loginModal) loginModal.classList.remove('hidden');
            if (loginEmailInput) loginEmailInput.value = '';
            if (loginPasswordInput) loginPasswordInput.value = '';
            if (loginErrorDisplay) {
                loginErrorDisplay.textContent = '';
                loginErrorDisplay.classList.remove('text-green-500');
                loginErrorDisplay.classList.add('text-red-500');
            }
        });
    }

    // *** Account button event listener ***
    if (accountBtn) {
        accountBtn.addEventListener('click', () => {
            if (accountModal) {
                accountModal.classList.remove('hidden');
                // Populate account details when modal opens
                const accountUidSpan = document.getElementById('account-uid');
                const accountPremiumStatusSpan = document.getElementById('account-premium-status');
                const accountNicknameInput = document.getElementById('account-nickname');

                if (auth && auth.currentUser) { // Check auth and currentUser before accessing
                    if (accountUidSpan) accountUidSpan.textContent = auth.currentUser.uid;
                    // For premium status and nickname, you would fetch from Firestore here as needed
                    // (This logic is already in onAuthStateChanged for initial load, but can be repeated here if needed for re-opening modal)
                }
            }
        });
    }

    // *** Change Password functionality ***
    if (updatePasswordBtn && auth) { // Ensure auth is initialized before attaching listener
        updatePasswordBtn.addEventListener('click', async (event) => {
            event.preventDefault();

            accountPasswordError.textContent = '';
            accountPasswordError.classList.remove('text-green-500');
            accountPasswordError.classList.add('text-red-500');

            const newPassword = accountNewPasswordInput.value;
            if (!newPassword) {
                accountPasswordError.textContent = 'Please enter a new password.';
                return;
            }

            const user = auth.currentUser;

            if (user) {
                /* // Password validation commented out as per your previous code
                try {
                    const passwordPolicyStatus = await validatePassword(auth, newPassword);
                    if (!passwordPolicyStatus.isValid) {
                        let feedback = "New password does not meet requirements: ";
                        if (passwordPolicyStatus.meetsMinPasswordLength === false) feedback += "minimum length, ";
                        if (passwordPolicyStatus.containsLowercaseLetter === false) feedback += "lowercase, ";
                        if (passwordPolicyStatus.containsUppercaseLetter === false) feedback += "uppercase, ";
                        if (passwordPolicyStatus.containsNumericCharacter === false) feedback += "numeric, ";
                        if (passwordPolicyStatus.containsNonAlphanumericCharacter === false) feedback += "special character, ";
                        loginErrorDisplay.textContent = feedback.slice(0, -2) + ".";
                        return;
                    }
                } catch (policyError) {
                    console.error("DEBUG: Error validating password policy:", policyError);
                    accountPasswordError.textContent = "Error checking password policy for new password.";
                    return;
                }
                */

                try {
                    await updatePassword(user, newPassword);
                    accountPasswordError.textContent = 'Password updated successfully!';
                    accountPasswordError.classList.remove('text-red-500');
                    accountPasswordError.classList.add('text-green-500');
                    accountNewPasswordInput.value = '';
                    console.log("DEBUG: User password updated.");
                } catch (error) {
                    console.error("DEBUG: Error updating password:", error.code, error.message);
                    accountPasswordError.classList.remove('text-green-500');
                    accountPasswordError.classList.add('text-red-500');
                    if (error.code === 'auth/weak-password') {
                        accountPasswordError.textContent = 'New password is too weak. Please choose a stronger one.';
                    } else if (error.code === 'auth/requires-recent-login') {
                         accountPasswordError.textContent = 'This is a security-sensitive operation. Please log out and log back in, then try changing your password again.';
                    } else {
                        accountPasswordError.textContent = `Error updating password: ${error.message}`;
                    }
                }
            } else {
                accountPasswordError.textContent = 'No user is currently logged in. Please log in to change your password.';
            }
        });
    }

    // *** Close Account Modal button listener ***
    const closeAccountModalBtn = document.getElementById('close-account-modal-btn');
    if (closeAccountModalBtn) {
        closeAccountModalBtn.addEventListener('click', () => {
            if (accountModal) {
                accountModal.classList.add('hidden');
                accountNewPasswordInput.value = '';
                accountPasswordError.textContent = '';
                accountPasswordError.classList.remove('text-green-500');
                accountPasswordError.classList.add('text-red-500');
            }
        });
    }

    const closeLoginModalBtn = document.getElementById('close-login-modal-btn');
    if (closeLoginModalBtn) {
        closeLoginModalBtn.addEventListener('click', () => {
            if (loginModal) loginModal.classList.add('hidden');
            if (loginErrorDisplay) {
                loginErrorDisplay.textContent = '';
                loginErrorDisplay.classList.remove('text-green-500');
                loginErrorDisplay.classList.add('text-red-500');
            }
            if (loginEmailInput) loginEmailInput.value = '';
            if (loginPasswordInput) loginPasswordInput.value = '';
        });
    }

    // --- Other initializations (e.g., QR Code generation) ---
    // Make sure qrcode.js library is loaded and QR code generation happens after DOMContentLoaded
    if (typeof QRCode !== 'undefined') {
        const loginQrcodeContainer = document.getElementById('login-qrcode');
        if (loginQrcodeContainer) {
            new QRCode(loginQrcodeContainer, {
                text: "https://your-app-domain.com/login-redirect?qr=true", // Replace with your actual QR login URL
                width: 100,
                height: 100,
                colorDark : "#000000",
                colorLight : "#ffffff",
                correctLevel : QRCode.CorrectLevel.H
            });
        }
        const cashappQrcodeContainer = document.getElementById('cashapp-qrcode');
        if (cashappQrcodeContainer) {
            new QRCode(cashappQrcodeContainer, {
                text: "$Mac100dime",
                width: 180,
                height: 180,
                colorDark : "#000000",
                colorLight : "#ffffff",
                correctLevel : QRCode.CorrectLevel.H
            });
        }
    } else {
        console.warn("DEBUG: qrcode.js library not loaded. QR code generation will not work.");
    }

    // Initialize any other UI components that don't depend on auth state
    const mainContent = document.getElementById('main-content');
    const paywallContent = document.getElementById('paywall-content');

    // Example: Initially hide main content and show paywall, then auth state will adjust
    // This logic might be better placed within your onAuthStateChanged listener
    // or triggered by it if it depends on user's PRO status.
    if (mainContent) mainContent.classList.add('hidden');
    if (paywallContent) paywallContent.classList.remove('hidden');
});