
#!/bin/bash

# Define the structure of the firebase config object
NETLIFY_FIREBASE_CONFIG="{
  apiKey: \"$FIREBASE_API_KEY\",
  authDomain: \"$FIREBASE_AUTH_DOMAIN\",
  projectId: \"$FIREBASE_PROJECT_ID\",
  storageBucket: \"$FIREBASE_STORAGE_BUCKET\",
  messagingSenderId: \"$FIREBASE_MESSAGING_SENDER_ID\",
  appId: \"$FIREBASE_APP_ID\"
}"

# Write the configuration files, exposing necessary variables globally
echo "
// This file is auto-generated by Netlify's build process from Environment Variables.

// Firebase Configuration (All keys needed for the client-side SDK)
window.NETLIFY_FIREBASE_CONFIG = $NETLIFY_FIREBASE_CONFIG;

// Gemini API Key (Accessed by client, or function)
window.GEMINI_API_KEY = \"$GEMINI_API_KEY\";

// A simplified App ID variable used in your debugging section
window.__app_id = \"$FIREBASE_APP_ID\";

" > ./env-config.js

echo "Successfully generated env-config.js"
