
// This file is auto-generated by Netlify's build process from Environment Variables.

// Firebase Configuration (All keys needed for the client-side SDK)
window.NETLIFY_FIREBASE_CONFIG = {
  apiKey: "",
  authDomain: "",
  projectId: "",
  storageBucket: "",
  messagingSenderId: "",
  appId: ""
};

// Gemini API Key (Accessed by client, or function)
window.GEMINI_API_KEY = "";

// A simplified App ID variable used in your debugging section
window.__app_id = "";


