
#!/bin/bash

# Function to strip extraneous quotes and commas from environment variables
strip_quotes() {
    # Uses sed to remove leading/trailing quotes (") and commas (,) from the value
    # and also trailing commas that might come from some environment variable systems.
    echo "$1" | sed -e 's/^"//' -e 's/"$//' -e 's/,$//' -e "s/^'//" -e "s/'$//"
}

echo "Creating env-config.js with configuration variables..."

# 1. Strip quotes and store CLEANED values from Netlify Environment Variables
API_KEY_CLEAN=$(strip_quotes "$FIREBASE_API_KEY")
AUTH_DOMAIN_CLEAN=$(strip_quotes "$FIREBASE_AUTH_DOMAIN")
PROJECT_ID_CLEAN=$(strip_quotes "$FIREBASE_PROJECT_ID")
STORAGE_BUCKET_CLEAN=$(strip_quotes "$FIREBASE_STORAGE_BUCKET")
MESSAGING_SENDER_ID_CLEAN=$(strip_quotes "$FIREBASE_MESSAGING_SENDER_ID")
APP_ID_CLEAN=$(strip_quotes "$FIREBASE_APP_ID")

# --- IMPORTANT SECURITY CONSIDERATIONS ---
# Directly exposing AUTH_TOKEN or highly privileged GEMINI_API_KEY in client-side JS
# is generally a security risk.
# For AUTH_TOKEN: If this is a user's session token or refresh token, it should
# be handled by the Firebase client SDK (e.g., firebase.auth().currentUser.getIdToken())
# and NOT exposed in static files. If it's a service account key for server-side use
# (e.g., Netlify Functions), it MUST NOT be exposed to the client.
# For GEMINI_API_KEY: If this key grants access to sensitive data or has broad permissions,
# consider proxying requests through a server-side function (e.g., a Netlify Function)
# to protect the key. If client-side use is unavoidable, ensure it's heavily restricted
# (e.g., HTTP referrer restrictions in Google Cloud Console).
AUTH_TOKEN_CLEAN=$(strip_quotes "$AUTH_TOKEN")
GEMINI_API_KEY_CLEAN=$(strip_quotes "$GEMINI_API_KEY")

# 2. Create the Firebase configuration JSON string.
# We use 'jq -n ... | jq -RToJson' to robustly create and then escape the JSON
# so it can be safely embedded as a JavaScript string literal.
# This prevents issues if any config values contain special characters (like quotes).
# NOTE: This requires 'jq' to be available in the build environment. Netlify usually includes it.
FIREBASE_CONFIG_JSON_ESCAPED=$(jq -n \
  --arg apiKey "$API_KEY_CLEAN" \
  --arg authDomain "$AUTH_DOMAIN_CLEAN" \
  --arg projectId "$PROJECT_ID_CLEAN" \
  --arg storageBucket "$STORAGE_BUCKET_CLEAN" \
  --arg messagingSenderId "$MESSAGING_SENDER_ID_CLEAN" \
  --arg appId "$APP_ID_CLEAN" \
  '{apiKey: $apiKey, authDomain: $authDomain, projectId: $projectId, storageBucket: $storageBucket, messagingSenderId: $messagingSenderId, appId: $appId}' | jq -RToJson)

# 3. Write all required variables to the env-config.js file
# This file will be generated in your project's root directory.
cat <<EOF > env-config.js
// THIS FILE IS AUTOMATICALLY GENERATED BY YOUR NETLIFY BUILD SCRIPT.
// DO NOT EDIT THIS FILE MANUALLY.

// WARNING: This file may contain sensitive API keys and tokens.
// Ensure this file is not publicly exposed unless necessary for client-side functionality,
// and that any API keys are properly restricted (e.g., by HTTP referrer).

// The Firebase Project ID variable, used in app.module.js for dynamic paths.
window.__project_id = '$PROJECT_ID_CLEAN';

// SECURITY WARNING: Re-evaluate if this token truly needs client-side exposure.
window.__initial_auth_token = '$AUTH_TOKEN_CLEAN';

// SECURITY WARNING: If this key is highly privileged, consider proxying via server-side functions.
window.GEMINI_API_KEY = '$GEMINI_API_KEY_CLEAN';

// The full Firebase object, now properly JSON-escaped for robust handling in app.js.
// Your client-side JavaScript can parse this using JSON.parse(window.__firebase_config);
window.__firebase_config = $FIREBASE_CONFIG_JSON_ESCAPED;

EOF

echo "✅ Successfully generated env-config.js with clean values."
